name: Build-Linux

on:
  push:
    branches: [master]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Embedding Python
        uses: ./.github/actions/setup-python-build
      - name: Build App
        uses: ./.github/actions/build-app
        with:
          platform: linux
          run-docs-build: 'false'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          main_vite_client_id: ${{ secrets.CLIENT_ID }}
          main_vite_client_secret: ${{ secrets.CLIENT_SECRET }}
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-deb
          path: dist/*.deb
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-rpm
          path: dist/*.rpm
